import Head from "next/head";

import { Button } from "@mui/material";

import { Speciality } from "@/components/speciality";
import { Testimonials } from "@/components/testimonials";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.banner}>
          Banner
          {/* <div>
          <Button variant="outlined" size="small">Outlined</Button>
          </div>   */}
        </div>
        <Speciality />
        <Testimonials />
    </main>
    </>
  );
}