import Head from "next/head";
import { Inter } from "next/font/google";

import { Header } from '@/components/header'
import { SubHeader } from "@/components/sub-header";

import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SubHeader />
        <div className={styles.content}>
          {/* <div style={{width: '60vw', height: 500, backgroundColor: "cyan"}}>`absavdhasjd</div>
          <div style={{width: '60vw', height: 700, backgroundColor: "yellow"}}></div> */}
        </div>
    </main>
    </>
  );
}
